{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
---
{{- end }}
