apiVersion: v1
kind: Secret
metadata:
  name: abandoned-config
  namespace: ecommerce
type: Opaque
stringData:
  webhookUrl: "http://n8n:5678/webhook/2ybUTjMaQSaoLIez/webhook/cart/abandoned"
  defaultEmail: "sodiqkunamin@gmail.com"
